### PR TITLE
Add tx paging for GET /block/:hash/with-txs (bitcoin_e)

### PR DESCRIPTION
**Pull request by shesek**

### CODE REVIEW

**Comment by shesek** [comment]
Note that this still deserializes the whole block, then discards the transactions outside of the requested range. Not deserializing these transactions to begin with would require making changes in `rust-{bitcoin,elements}`'s deserializer implementation (`bitcoin::consensus::encode`, formerly `bitcoin::network::serialize`).

**Review by RCasatta — COMMENTED** [review]
I am not sure we should use paging parameters in the query string, cause could invalidate caching

**Comment by shesek** [comment]
@RCasatta its a matter of configuration, nginx can be told to include the query string in the cache key via `proxy_cache_key`

**Comment by greenaddress** [comment]
merged

**Comment by RCasatta** [comment]
It's not just a matter of configuration of your nginx, remember that we ha have nginx caching but we would setup also http public caching, and the latter could be potentially cached around on ISP servers/routers. So it matters

**Pull request closed without merging**
